### ISSUE TITLE
Acceso al github

### ISSUE THREAD

**Issue by Andtl** [Andtl/EL5002#1]
Comenten para ser agregados al proyecto.

**Comment by fadax77** [comment]
Hola, soy Fabián Navarro. Agréguenme.

**Comment by juanolete** [comment]
Soy Juan Millán

**Comment by oscarpimentel** [comment]
Hola! Soy Oscar :)

**Comment by jear300** [comment]
hola soy Juan Arias

**Comment by camiloelsaldi** [comment]
soy el saldi, agregame andreeeees

**Comment by Tino-HG** [comment]
hola soy el tino 🐸

**Comment by SpeitK** [comment]
Soy Felipe, agreguenme pls

**Comment by pablo512** [comment]
Holi, soy Pablo Morales.

**Comment by eduardo-barria** [comment]
Hola, soy Eduardo Barría.

**Comment by ignazau** [comment]
Hola, perdón por la mega tardanza, soy Ignacio Bugueño

**Comment by nicosepu** [comment]
Hola, soy Nicolás Sepúlveda. Agrenguenme plis

**Comment by lozapablo** [comment]
hola <3, Pablo Loza
